1:
  robot1:
    x:   0.0
    y:  -2.0
    yaw: 1.6

2:
  robot1:
    x:   0.0
    y:  -2.0
    yaw: 1.59
  robot2:
    x:  -2.0
    y:  -2.0
    yaw: 1.59

3:
  robot1:
    x:   0.0
    y:  -2.0
    yaw: 1.59
  robot2:
    x:  -2.0
    y:  -2.0
    yaw: 1.59
  robot3:
    x:   2.0
    y:  -2.0
    yaw: 1.59